### ISSUE TITLE
Doesn't load in code editor

### ISSUE THREAD

**Issue by jotade94** [lukechadwick/Liquify#29]
Like every day, I go to edit code from different stores and none of the extra features it adds appear.

Especially the search engine and black mode do not work (although the search engine is the most important thing).

I have tried from Brave and Chrome in addition to clearing the cookie and going private in both browsers.

**Comment by PresidioBobby** [comment]
Hey, I've been running into the same issue working on different stores as well. It happens to some and not to others.

So far, the only thing I can see is that when it works, the store URL is still using 'myshopfiy.com'. There is a new update from Shopify that might get pushed out where the URL changes and it's now 'admin.shopify.com/store/store-name'.

Just a stab in the dark but hope it helps, hope we can see a patch soon, great extension overall!

**Comment by lukechadwick** [comment]
Hey guys, thanks for reporting.  I believe this is related to #28 with the new URL format as the extension isn't looking for that URL.  I've been keeping an eye on this as none of my clients had the new URL format so I wasn't able to reproduce.  I've since found a store that has the new URL format so should be able to update this soon.

**Comment by lukechadwick** [comment]
Solving in #28
