### ISSUE TITLE
Liquify extension doesn't working after shopify update 01.07.2022

### ISSUE THREAD

**Issue by reajkee13** [lukechadwick/Liquify#9]

**Comment by lukechadwick** [comment]
Hi, can you provide some more info or console log errors if any?

Still working here

![image](https://user-images.githubusercontent.com/6725655/177502318-0d70b35b-40fd-4bed-a2fe-328c55e12d93.png)

**Comment by lukechadwick** [comment]
Hi there, it looks like your image didn't upload.  Sure try a reinstall and or incognito, or try in a regular Shopify theme from the store.

I work on many different stores (plus and regular) and it still working on all of them. It's possible you have access to a beta feature or something that hasn't been rolled out yet to all stores but without access I can't see what the issue is.

**Comment by reajkee13** [comment]
Hi there, looks like you are right "It's possible you have access to a beta
feature or something that hasn't been rolled out yet to all stores" because
I tried on a few other stores and everything worked fine!
Hope they will update all stores and you can fix the issue. Thanks

чт, 7 лип. 2022 р. о 03:32 Luke Chadwick ***@***.***> пише:

**Comment by reajkee13** [comment]
Awesome, thanks!

ср, 13 лип. 2022 р. о 07:03 Luke Chadwick ***@***.***> пише:

**Comment by lukechadwick** [comment]
There have been some pretty significant changes to the code editor.  I have fixed some of the core functionality (themes/codesearch), will try get a release out tonight with the basics then work on the less important stuff.

**Comment by reajkee13** [comment]
Hi there, great!
Keep me updated.
Thanks!
